# Generated by Django 5.0.4 on 2024-05-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_searched_at',
        ),
    ]
