# Generated by Django 5.0.4 on 2024-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_scraper_app', '0002_remove_user_last_searched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='last_searched_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
