# Generated by Django 5.0.4 on 2024-05-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_scraper_app', '0003_alter_search_last_searched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ml_scraper_app.product'),
        ),
    ]
